"""Contract and real-weight smoke tests for the local CHESTER runtime."""
from __future__ import annotations

import numpy as np
import pytest
from pydicom.dataset import Dataset, FileMetaDataset
from pydicom.uid import ExplicitVRLittleEndian

from app.chester_runtime import ChesterModel, MODEL_VERSION
from app.dicom_utils import render_dicom_frame_for_chester


def _gradient_fixture() -> np.ndarray:
    return np.linspace(64, 191, 224 * 224, dtype=np.float32).reshape(224, 224)


def test_chester_preprocessing_contract():
    model = ChesterModel()

    prepared = model.preprocess(_gradient_fixture())

    assert prepared.shape == (224, 224)
    assert prepared.dtype == np.float32
    assert np.isfinite(prepared).all()
    assert prepared[0, 0] == pytest.approx((64 / 255 * 2 - 1) * 1024)
    assert prepared[-1, -1] == pytest.approx((191 / 255 * 2 - 1) * 1024)
    assert prepared[0, 0] < prepared[-1, -1]


def test_chester_preprocessing_does_not_stretch_contrast():
    model = ChesterModel()
    narrow = np.full((224, 224), 128, dtype=np.float32)

    prepared = model.preprocess(narrow)

    expected = (
        np.float32(128) / np.float32(255) * np.float32(2)
        - np.float32(1)
    ) * np.float32(1024)
    assert np.allclose(prepared, expected, rtol=1e-7, atol=1e-5)
    assert prepared.min() > -1024
    assert prepared.max() < 1024


def test_dicom_render_uses_window_bounds_and_eight_bit_quantization():
    pixels = np.array([[100, 150], [200, 250]], dtype=np.uint16)
    dataset = Dataset()
    dataset.file_meta = FileMetaDataset()
    dataset.file_meta.TransferSyntaxUID = ExplicitVRLittleEndian
    dataset.Rows = 2
    dataset.Columns = 2
    dataset.SamplesPerPixel = 1
    dataset.PhotometricInterpretation = "MONOCHROME2"
    dataset.BitsAllocated = 16
    dataset.BitsStored = 16
    dataset.HighBit = 15
    dataset.PixelRepresentation = 0
    dataset.WindowCenter = 200
    dataset.WindowWidth = 400
    dataset.PixelData = pixels.tobytes()

    rendered = render_dicom_frame_for_chester(dataset)

    expected = np.rint(pixels.astype(np.float32) / 400 * 255)
    assert np.array_equal(rendered, expected)
    # The narrow source range must not be stretched to the full 0..255 range.
    assert rendered.min() > 0
    assert rendered.max() < 255


def test_chester_real_weights_are_deterministic():
    model = ChesterModel(timeout_seconds=120)
    expected = np.array(
        [
            0.332059264,
            0.153833821,
            0.149081379,
            0.035177320,
            0.076061234,
            0.019156404,
            0.019912250,
            0.367418617,
            0.266114444,
            0.104356349,
            0.169735298,
            0.037298437,
            0.079548687,
            0.013984763,
            0.055640470,
            0.056109272,
            0.425459236,
            0.207474649,
        ],
        dtype=np.float32,
    )

    try:
        first = model.infer(_gradient_fixture())
        second = model.infer(_gradient_fixture())
    finally:
        model.close()

    assert model.version == MODEL_VERSION
    assert first.shape == (18,)
    assert np.isfinite(first).all()
    assert np.array_equal(first, second)
    # Golden vector generated by the checked-in TensorFlow.js 2.0.1 legacy
    # runtime from the same 0..255 fixture and CHESTER input transform.
    assert np.allclose(first, expected, rtol=2e-4, atol=2e-6)