"""initial schema

Revision ID: 06aa4180ea1d
Revises:
Create Date: 2026-08-25 03:10:05.091358
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "06aa4180ea1d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_control_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_email", sa.String(length=320), nullable=False),
        sa.Column("actor_role", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_key", sa.String(length=320), nullable=False),
        sa.Column("target_role", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("access_control_audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_access_control_audit_log_actor_email"), ["actor_email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_access_control_audit_log_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "auth_challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_ip", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_challenges_email"), ["email"], unique=False)
        batch_op.create_index(
            "ix_auth_challenges_email_requested", ["email", "requested_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auth_challenges_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auth_challenges_requested_at"), ["requested_at"], unique=False
        )

    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)

    op.create_table(
        "allowed_domains",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("allowed_pages", sa.JSON(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allowed_domains", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_allowed_domains_domain"), ["domain"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_allowed_domains_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("allowed_pages", sa.JSON(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_env_admin", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("request_ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auth_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "studies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.String(length=128), nullable=True),
        sa.Column("patient_age", sa.String(length=16), nullable=True),
        sa.Column("patient_sex", sa.String(length=8), nullable=True),
        sa.Column("study_date", sa.String(length=16), nullable=True),
        sa.Column("modality", sa.String(length=16), nullable=True),
        sa.Column("view_position", sa.String(length=16), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("validation_state", sa.String(length=32), nullable=True),
        sa.Column("validation_reason", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("preprocessing_version", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("study_instance_uid", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("studies", schema=None) as batch_op:
        batch_op.create_index(
            "ix_studies_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_studies_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index("ix_studies_owner_status", ["owner_user_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_studies_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_studies_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_studies_study_instance_uid"), ["study_instance_uid"], unique=False
        )

    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_jobs_lease_expires_at"), ["lease_expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_jobs_study_id"), ["study_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=320), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_actor"), ["actor"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_study_id"), ["study_id"], unique=False)

    op.create_table(
        "instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("sop_instance_uid", sa.String(length=128), nullable=True),
        sa.Column("sop_class_uid", sa.String(length=128), nullable=True),
        sa.Column("series_instance_uid", sa.String(length=128), nullable=True),
        sa.Column("transfer_syntax_uid", sa.String(length=128), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("columns", sa.Integer(), nullable=True),
        sa.Column("bits_allocated", sa.Integer(), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=64), nullable=True),
        sa.Column("audit_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sop_instance_uid"),
    )
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instances_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_instances_study_id"), ["study_id"], unique=False)

    op.create_table(
        "analysis_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("preprocessing_version", sa.String(length=64), nullable=True),
        sa.Column("raw_scores", sa.JSON(), nullable=True),
        sa.Column("op_normalized_scores", sa.JSON(), nullable=True),
        sa.Column("thresholds", sa.JSON(), nullable=True),
        sa.Column("above_threshold", sa.JSON(), nullable=True),
        sa.Column("above_threshold_findings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_results_study_id"), ["study_id"], unique=False
        )

    op.create_table(
        "stored_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("storage_backend", sa.String(length=32), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("inline_data", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["instance_id"], ["instances.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stored_objects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stored_objects_instance_id"), ["instance_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stored_objects_object_key"), ["object_key"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_objects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stored_objects_object_key"))
        batch_op.drop_index(batch_op.f("ix_stored_objects_instance_id"))

    op.drop_table("stored_objects")
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_results_study_id"))

    op.drop_table("analysis_results")
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instances_study_id"))
        batch_op.drop_index(batch_op.f("ix_instances_sha256"))

    op.drop_table("instances")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_study_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor"))

    op.drop_table("audit_events")
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_study_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_lease_expires_at"))

    op.drop_table("analysis_jobs")
    with op.batch_alter_table("studies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_studies_study_instance_uid"))
        batch_op.drop_index(batch_op.f("ix_studies_status"))
        batch_op.drop_index(batch_op.f("ix_studies_owner_user_id"))
        batch_op.drop_index("ix_studies_owner_status")
        batch_op.drop_index(batch_op.f("ix_studies_organization_id"))
        batch_op.drop_index("ix_studies_org_created")

    op.drop_table("studies")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_expires_at"))

    op.drop_table("auth_sessions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_organization_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("allowed_domains", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allowed_domains_organization_id"))
        batch_op.drop_index(batch_op.f("ix_allowed_domains_domain"))

    op.drop_table("allowed_domains")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))

    op.drop_table("organizations")
    with op.batch_alter_table("auth_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_challenges_requested_at"))
        batch_op.drop_index(batch_op.f("ix_auth_challenges_expires_at"))
        batch_op.drop_index("ix_auth_challenges_email_requested")
        batch_op.drop_index(batch_op.f("ix_auth_challenges_email"))

    op.drop_table("auth_challenges")
    with op.batch_alter_table("access_control_audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_access_control_audit_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_access_control_audit_log_actor_email"))

    op.drop_table("access_control_audit_log")
    # ### end Alembic commands ###
