"""localize validation reasons

Revision ID: c9d294c53c45
Revises: e4a178f113e6
Create Date: 2026-08-25 14:38:52.612993
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations may reference the project's custom column types by their full path.
import chester.db  # noqa: F401


revision: str = "c9d294c53c45"
down_revision: str | None = "e4a178f113e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("studies", sa.Column("body_part", sa.String(length=64), nullable=True))
    op.add_column(
        "studies", sa.Column("validation_reason_code", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("studies", "validation_reason_code")
    op.drop_column("studies", "body_part")
    # ### end Alembic commands ###
