"""initial schema

Revision ID: e4a178f113e6
Revises:
Create Date: 2026-08-25 03:31:18.529787
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations may reference the project's custom column types by their full path.
import chester.db  # noqa: F401


revision: str = "e4a178f113e6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


LEGACY_ARCHIVE_SCHEMA = "chester_legacy_archive"
LEGACY_TABLES = (
    "access_control_audit_log",
    "allowed_domains",
    "allowed_emails",
    "analysis_jobs",
    "analysis_results",
    "audit_events",
    "auth_challenges",
    "auth_sessions",
    "instances",
    "legacy_owner_aliases",
    "stored_objects",
    "studies",
)


def _archive_legacy_schema() -> None:
    """Move the incompatible pre-Alembic schema aside before fresh setup."""

    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    inspector = sa.inspect(bind)
    public_tables = set(inspector.get_table_names(schema="public"))
    if "alembic_version" in public_tables:
        recorded_revision = bind.execute(
            sa.text("SELECT version_num FROM alembic_version")
        ).scalar()
        if recorded_revision:
            return

    if "studies" not in public_tables:
        conflicting = public_tables.intersection(LEGACY_TABLES)
        if conflicting:
            names = ", ".join(sorted(conflicting))
            raise RuntimeError(
                "Found an unversioned, incomplete Chester schema "
                f"({names}). Restore it or archive it before running migrations."
            )
        return

    study_columns = {column["name"] for column in inspector.get_columns("studies")}
    if "owner_id" not in study_columns or "owner_user_id" in study_columns:
        raise RuntimeError(
            "Found an unversioned studies table that is not the supported legacy schema. "
            "Refusing to archive an unrecognized schema automatically."
        )

    archive_tables: set[str] = set()
    if LEGACY_ARCHIVE_SCHEMA in inspector.get_schema_names():
        archive_tables = set(inspector.get_table_names(schema=LEGACY_ARCHIVE_SCHEMA))
    conflicts = archive_tables.intersection(LEGACY_TABLES)
    if conflicts:
        names = ", ".join(sorted(conflicts))
        raise RuntimeError(
            f"Legacy archive schema already contains {names}. "
            "Inspect the archived data before retrying the migration."
        )

    if LEGACY_ARCHIVE_SCHEMA not in inspector.get_schema_names():
        op.execute(sa.text(f'CREATE SCHEMA "{LEGACY_ARCHIVE_SCHEMA}"'))

    for table_name in LEGACY_TABLES:
        if table_name in public_tables:
            op.execute(
                sa.text(f'ALTER TABLE public."{table_name}" SET SCHEMA "{LEGACY_ARCHIVE_SCHEMA}"')
            )


def upgrade() -> None:
    _archive_legacy_schema()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_control_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_email", sa.String(length=320), nullable=False),
        sa.Column("actor_role", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_key", sa.String(length=320), nullable=False),
        sa.Column("target_role", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_control_audit_log")),
    )
    op.create_index(
        op.f("ix_access_control_audit_log_actor_email"),
        "access_control_audit_log",
        ["actor_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_control_audit_log_created_at"),
        "access_control_audit_log",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "auth_challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", chester.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("requested_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("request_ip", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_challenges")),
    )
    op.create_index(op.f("ix_auth_challenges_email"), "auth_challenges", ["email"], unique=False)
    op.create_index(
        "ix_auth_challenges_email_requested",
        "auth_challenges",
        ["email", "requested_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_challenges_expires_at"), "auth_challenges", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_challenges_requested_at"), "auth_challenges", ["requested_at"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "allowed_domains",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("allowed_pages", sa.JSON(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_allowed_domains_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allowed_domains")),
    )
    op.create_index(op.f("ix_allowed_domains_domain"), "allowed_domains", ["domain"], unique=True)
    op.create_index(
        op.f("ix_allowed_domains_organization_id"),
        "allowed_domains",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("allowed_pages", sa.JSON(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_env_admin", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", chester.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("request_ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_token_hash"), "auth_sessions", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "studies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.String(length=128), nullable=True),
        sa.Column("patient_age", sa.String(length=16), nullable=True),
        sa.Column("patient_sex", sa.String(length=8), nullable=True),
        sa.Column("study_date", sa.String(length=16), nullable=True),
        sa.Column("modality", sa.String(length=16), nullable=True),
        sa.Column("view_position", sa.String(length=16), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("validation_state", sa.String(length=32), nullable=True),
        sa.Column("validation_reason", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("preprocessing_version", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("study_instance_uid", sa.String(length=128), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_studies_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_studies_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studies")),
    )
    op.create_index(
        "ix_studies_org_created", "studies", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_studies_organization_id"), "studies", ["organization_id"], unique=False
    )
    op.create_index("ix_studies_owner_status", "studies", ["owner_user_id", "status"], unique=False)
    op.create_index(op.f("ix_studies_owner_user_id"), "studies", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_studies_status"), "studies", ["status"], unique=False)
    op.create_index(
        op.f("ix_studies_study_instance_uid"), "studies", ["study_instance_uid"], unique=False
    )
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", chester.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("started_at", chester.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("completed_at", chester.db.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_analysis_jobs_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
    )
    op.create_index(
        op.f("ix_analysis_jobs_lease_expires_at"),
        "analysis_jobs",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(op.f("ix_analysis_jobs_status"), "analysis_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_analysis_jobs_study_id"), "analysis_jobs", ["study_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=320), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_audit_events_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_actor"), "audit_events", ["actor"], unique=False)
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_events_study_id"), "audit_events", ["study_id"], unique=False)
    op.create_table(
        "instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("sop_instance_uid", sa.String(length=128), nullable=True),
        sa.Column("sop_class_uid", sa.String(length=128), nullable=True),
        sa.Column("series_instance_uid", sa.String(length=128), nullable=True),
        sa.Column("transfer_syntax_uid", sa.String(length=128), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("columns", sa.Integer(), nullable=True),
        sa.Column("bits_allocated", sa.Integer(), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=64), nullable=True),
        sa.Column("audit_note", sa.Text(), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_instances_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_instances_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instances")),
        sa.UniqueConstraint("organization_id", "sop_instance_uid", name="uq_instances_org_sop_uid"),
    )
    op.create_index(
        "ix_instances_org_sha256", "instances", ["organization_id", "sha256"], unique=False
    )
    op.create_index(
        op.f("ix_instances_organization_id"), "instances", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_instances_sha256"), "instances", ["sha256"], unique=False)
    op.create_index(op.f("ix_instances_study_id"), "instances", ["study_id"], unique=False)
    op.create_table(
        "analysis_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("preprocessing_version", sa.String(length=64), nullable=True),
        sa.Column("raw_scores", sa.JSON(), nullable=True),
        sa.Column("op_normalized_scores", sa.JSON(), nullable=True),
        sa.Column("thresholds", sa.JSON(), nullable=True),
        sa.Column("above_threshold", sa.JSON(), nullable=True),
        sa.Column("above_threshold_findings", sa.JSON(), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_analysis_results_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_analysis_results_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_results")),
        sa.UniqueConstraint("job_id", name=op.f("uq_analysis_results_job_id")),
    )
    op.create_index(
        op.f("ix_analysis_results_study_id"), "analysis_results", ["study_id"], unique=False
    )
    op.create_table(
        "stored_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("storage_backend", sa.String(length=32), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("inline_data", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", chester.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_stored_objects_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_objects")),
    )
    op.create_index(
        op.f("ix_stored_objects_instance_id"), "stored_objects", ["instance_id"], unique=False
    )
    op.create_index(
        op.f("ix_stored_objects_object_key"), "stored_objects", ["object_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stored_objects_object_key"), table_name="stored_objects")
    op.drop_index(op.f("ix_stored_objects_instance_id"), table_name="stored_objects")
    op.drop_table("stored_objects")
    op.drop_index(op.f("ix_analysis_results_study_id"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_instances_study_id"), table_name="instances")
    op.drop_index(op.f("ix_instances_sha256"), table_name="instances")
    op.drop_index(op.f("ix_instances_organization_id"), table_name="instances")
    op.drop_index("ix_instances_org_sha256", table_name="instances")
    op.drop_table("instances")
    op.drop_index(op.f("ix_audit_events_study_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_analysis_jobs_study_id"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_status"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_lease_expires_at"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_studies_study_instance_uid"), table_name="studies")
    op.drop_index(op.f("ix_studies_status"), table_name="studies")
    op.drop_index(op.f("ix_studies_owner_user_id"), table_name="studies")
    op.drop_index("ix_studies_owner_status", table_name="studies")
    op.drop_index(op.f("ix_studies_organization_id"), table_name="studies")
    op.drop_index("ix_studies_org_created", table_name="studies")
    op.drop_table("studies")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token_hash"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_allowed_domains_organization_id"), table_name="allowed_domains")
    op.drop_index(op.f("ix_allowed_domains_domain"), table_name="allowed_domains")
    op.drop_table("allowed_domains")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_auth_challenges_requested_at"), table_name="auth_challenges")
    op.drop_index(op.f("ix_auth_challenges_expires_at"), table_name="auth_challenges")
    op.drop_index("ix_auth_challenges_email_requested", table_name="auth_challenges")
    op.drop_index(op.f("ix_auth_challenges_email"), table_name="auth_challenges")
    op.drop_table("auth_challenges")
    op.drop_index(
        op.f("ix_access_control_audit_log_created_at"), table_name="access_control_audit_log"
    )
    op.drop_index(
        op.f("ix_access_control_audit_log_actor_email"), table_name="access_control_audit_log"
    )
    op.drop_table("access_control_audit_log")
    # ### end Alembic commands ###
